# reposynth configuration
# Generated by: reposynth init
# Edit before running: reposynth generate

# Languages detected in this repo (add or remove as needed)
languages:
{{languages}}

# LLM provider configuration
provider:
  # anthropic | openai
  type: anthropic
  # Model to use for generation
  model: claude-sonnet-4-6
  # Leave null to use the default endpoint for the type above,
  # or set to a proxy URL (e.g. https://llm-proxy.internal)
  base_url: ~
  # Name of the environment variable holding your API key
  api_key_env: ANTHROPIC_API_KEY

# Where to find convention rule markdown files (relative to repo root)
# reposynth will discover all *.md files recursively under this path
conventions_dir: .claude/rules

# Pattern catalog file (copied from reposynth templates on init)
# Edit to add/remove patterns for your codebase
patterns_file: .reposynth/patterns/go.yaml

# Where generated JSONL files are written
output_dir: .reposynth/data

# Number of training variations to generate per source
generate:
  # Variations generated per rule .md file
  rules_per_file: 5
  # Variations generated per booster pattern entry
  booster_n: 8
  # Max concurrent LLM calls
  concurrency: 3

# Data quality thresholds (used by: reposynth check)
health:
  go:
    # Minimum % of Go code fences that must start with 'func'
    func_start_pct: 85
    # Minimum occurrences per tracked library pattern
    min_pattern_coverage: 20

# Optional: freeform context injected into every generation prompt.
# Describe your repo's conventions, import paths, mandatory libraries, etc.
# If blank, a generic prompt is used.
codebase_context: |
  Repository: <your-org>/<your-repo>

  Add your key conventions here:
  - Mandatory import paths
  - Libraries to always/never use
  - Error handling conventions
  - Logging patterns

# Optional: override the system identity prompt
# system_prompt: "You are a coding assistant for <org> following our conventions."
